import test from 'node:test';import assert from 'node:assert/strict';import {decodeTree,encodeTree} from '../public/algorithm-cards/shared/tree-card.js';
const ids=['215','295','394','146','101','124','108','105','114','437','236'];
const modules=new Map(await Promise.all(ids.map(async id=>[id,{...await import(`../public/algorithm-cards/problems/${id}.js`),codes:(await import(`../public/algorithm-cards/problems/${id}-code.js`)).codes}])));
class TreeNode{constructor(val=0,left=null,right=null){Object.assign(this,{val,left,right});}}
const solve=id=>{const c=modules.get(id).codes[1];return new Function('TreeNode',`${c.source};return ${c.operationClass??c.method};`)(TreeNode);};
test('heap selection and data stream medians agree with independent sorting',()=>{const kth=solve('215'),Finder=solve('295');let seed=215;const random=n=>((seed=(seed*1664525+1013904223)>>>0)%n);const finder=new Finder(),values=[],operations=[['MedianFinder',[]]],expected=[null];for(let i=0;i<200;i++){const value=random(200001)-100000;values.push(value);finder.addNum(value);operations.push(['addNum',[value]],['findMedian',[]]);const sorted=[...values].sort((a,b)=>a-b),median=sorted.length%2?sorted[Math.floor(sorted.length/2)]:(sorted[sorted.length/2-1]+sorted[sorted.length/2])/2;assert.equal(finder.findMedian(),median);expected.push(null,median);const k=1+random(values.length);assert.equal(kth(values,k),sorted.at(-k));}assert.deepEqual(modules.get('295').buildTrace({operations}).at(-1).answer,expected);assert.equal(kth(Array(100000).fill(-10000),100000),-10000);});
test('LRU source and trace agree with a simple array-based reference',()=>{const Cache=solve('146');for(const capacity of [1,2,5]){const cache=new Cache(capacity),entries=[],operations=[['LRUCache',[capacity]]],expected=[null];for(let i=0;i<100;i++){const key=(i*7)%9,write=i%3!==0,value=i;const index=entries.findIndex(([k])=>k===key);if(write){if(index>=0)entries.splice(index,1);entries.push([key,value]);if(entries.length>capacity)entries.shift();cache.put(key,value);operations.push(['put',[key,value]]);expected.push(null);}else{let result=-1;if(index>=0){const entry=entries.splice(index,1)[0];entries.push(entry);result=entry[1];}assert.equal(cache.get(key),result);operations.push(['get',[key]]);expected.push(result);}}assert.deepEqual(modules.get('146').buildTrace({operations}).at(-1).answer,expected);}});
test('nested decoder matches an independent recursive parser including maximum repeat',()=>{const decode=solve('394');function reference(s){let i=0;function parse(){let out='';while(i<s.length&&s[i]!==']'){if(/\d/.test(s[i])){let n=0;while(/\d/.test(s[i]??''))n=n*10+Number(s[i++]);i++;const part=parse();i++;out+=part.repeat(n);}else out+=s[i++];}return out;}return parse();}for(const s of ['3[a2[c]]','12[a]','x2[ab]y','2[a3[b]c]4[de]','300[a]']){assert.equal(decode(s),reference(s));assert.equal(modules.get('394').buildTrace({s}).at(-1).answer,reference(s));}});
const preorder=node=>node?[node.val,...preorder(node.left),...preorder(node.right)]:[];
const inorder=node=>node?[...inorder(node.left),node.val,...inorder(node.right)]:[];
test('tree construction preserves traversals and sorted-array trees are balanced',()=>{for(let n=1;n<=31;n++){const nums=Array.from({length:n},(_,i)=>i*2-31),tree=solve('108')(nums);assert.deepEqual(inorder(tree),nums);function height(node){if(!node)return 0;const a=height(node.left),b=height(node.right);assert.ok(Math.abs(a-b)<=1);return Math.max(a,b)+1;}height(tree);assert.deepEqual(modules.get('108').buildTrace({nums}).at(-1).answer,encodeTree(tree));const pre=preorder(tree),ino=inorder(tree),rebuilt=solve('105')(pre,ino);assert.deepEqual(encodeTree(rebuilt),encodeTree(tree));assert.deepEqual(modules.get('105').buildTrace({preorder:pre,inorder:ino}).at(-1).answer,encodeTree(tree));}});
test('flatten keeps the exact original nodes and follows preorder',()=>{const flatten=solve('114');for(const e of modules.get('114').examples){const tree=decodeTree(e.input),nodes=[];function visit(n){if(n){nodes.push(n);visit(n.left);visit(n.right);}}visit(tree);assert.equal(flatten(tree),undefined);let current=tree;for(const n of nodes){assert.equal(current,n);assert.equal(n.left,null);current=n.right;}assert.equal(current,null);assert.deepEqual(modules.get('114').buildTrace(e).at(-1).answer,encodeTree(tree));}});
test('tree sums, symmetry and common ancestors match independent small-tree references',()=>{for(let trial=1;trial<=50;trial++){const input=Array.from({length:1+trial%11},(_,i)=>(i*7+trial)%9-4),tree=decodeTree(input),targetSum=trial%7-3,nodes=[],parent=new Map();function walk(n,p=null){if(n){nodes.push(n);parent.set(n,p);walk(n.left,n);walk(n.right,n);}}walk(tree);function down(n,total){if(!n)return 0;total+=n.val;return Number(total===targetSum)+down(n.left,total)+down(n.right,total);}const count=nodes.reduce((a,n)=>a+down(n,0),0);assert.equal(solve('437')(tree,targetSum),count);assert.equal(modules.get('437').buildTrace({input,targetSum}).at(-1).answer,count);let best=-Infinity;for(const start of nodes){function path(n,from,sum){sum+=n.val;best=Math.max(best,sum);for(const next of [n.left,n.right,parent.get(n)])if(next&&next!==from)path(next,n,sum);}path(start,null,0);}assert.equal(solve('124')(tree),best);assert.equal(modules.get('124').buildTrace({input}).at(-1).answer,best);function mirror(a,b){return !a||!b?a===b:a.val===b.val&&mirror(a.left,b.right)&&mirror(a.right,b.left);}assert.equal(solve('101')(tree),mirror(tree,tree));assert.equal(modules.get('101').buildTrace({input}).at(-1).answer,mirror(tree,tree));}
 const input=[3,5,1,6,2,0,8,null,null,7,4],tree=decodeTree(input),nodes=[],parent=new Map();function visit(n,p=null){if(n){nodes.push(n);parent.set(n,p);visit(n.left,n);visit(n.right,n);}}visit(tree);for(const p of nodes)for(const q of nodes)if(p!==q){const ancestors=new Set();for(let n=p;n;n=parent.get(n))ancestors.add(n);let expected=q;while(!ancestors.has(expected))expected=parent.get(expected);assert.equal(solve('236')(tree,p,q),expected);assert.equal(modules.get('236').buildTrace({input,p:p.val,q:q.val}).at(-1).answer,expected.val);}});
test('new tree heap cache phases map separately in every language',()=>{for(const [id,m] of modules)for(const e of m.examples)for(const s of m.buildTrace(e))for(const c of m.codes)assert.ok(c.source.split('\n')[c.lines[s.line]-1]?.trim(),`${id} ${c.id} ${s.line}`);});
