import test from 'node:test';import assert from 'node:assert/strict';
const ids=['131','51','79','25','148','23','138'];const modules=new Map(await Promise.all(ids.map(async id=>[id,{...await import(`../public/algorithm-cards/problems/${id}.js`),codes:(await import(`../public/algorithm-cards/problems/${id}-code.js`)).codes}])));
class ListNode{constructor(val=0,next=null){Object.assign(this,{val,next});}}class Node{constructor(val=0,next=null,random=null){Object.assign(this,{val,next,random});}}
const solve=id=>{const c=modules.get(id).codes[1];return new Function('ListNode','Node',`${c.source};return ${c.method};`)(ListNode,Node);};
const linked=values=>values.reduceRight((next,val)=>new ListNode(val,next),null);
function nodes(head){const result=[];while(head){assert.ok(!result.includes(head),'unexpected cycle');result.push(head);head=head.next;}return result;}
test('reverse groups and merge sorting preserve all original node identities',()=>{let seed=148;const random=n=>((seed=(seed*1664525+1013904223)>>>0)%n);for(let trial=0;trial<150;trial++){const input=Array.from({length:1+random(15)},()=>random(15)-7),k=1+random(input.length),head=linked(input),original=nodes(head),result=nodes(solve('25')(head,k)),expected=[];for(let i=0;i<input.length;i+=k)expected.push(...original.slice(i,i+k)[i+k<=input.length?'reverse':'slice']());assert.deepEqual(result,expected);assert.deepEqual(modules.get('25').buildTrace({input,k}).at(-1).answer,expected.map(n=>n.val));const sortedHead=linked(input),sortOriginal=nodes(sortedHead),sortResult=nodes(solve('148')(sortedHead));assert.deepEqual(sortResult.map(n=>n.val),[...input].sort((a,b)=>a-b));assert.deepEqual(new Set(sortResult),new Set(sortOriginal));assert.deepEqual(modules.get('148').buildTrace({input}).at(-1).answer,sortResult.map(n=>n.val));const lists=Array.from({length:random(8)},()=>Array.from({length:random(7)},()=>random(15)-7).sort((a,b)=>a-b)),heads=lists.map(linked),all=heads.flatMap(nodes),merged=nodes(solve('23')(heads));assert.deepEqual(merged.map(n=>n.val),lists.flat().sort((a,b)=>a-b));assert.deepEqual(new Set(merged),new Set(all));assert.deepEqual(modules.get('23').buildTrace({lists}).at(-1).answer,merged.map(n=>n.val));}assert.equal(solve('148')(null),null);assert.equal(solve('23')([]),null);});
test('random-list copies have independent identities and identical pointer topology',()=>{for(const e of modules.get('138').examples){const originals=e.input.map(([v])=>new Node(v));originals.forEach((n,i)=>{n.next=originals[i+1]??null;n.random=originals[e.input[i][1]]??null;});const pointers=originals.map(n=>[n.next,n.random]),copies=nodes(solve('138')(originals[0]??null));assert.equal(copies.length,originals.length);copies.forEach((n,i)=>{assert.ok(!originals.includes(n));assert.equal(n.val,originals[i].val);assert.equal(n.next,copies[i+1]??null);assert.equal(n.random,e.input[i][1]===null?null:copies[e.input[i][1]]);});assert.deepEqual(originals.map(n=>[n.next,n.random]),pointers);const trace=modules.get('138').buildTrace(e),final=trace.at(-1);for(const n of final.nodes.filter(n=>n.id.startsWith('C')))for(const field of ['next','random'])assert.ok(n[field]===null||n[field].startsWith('C'));assert.deepEqual(final.answer,e.input);assert.equal(trace[0].nodes.length,e.input.length);}});
test('palindrome partitions match all cut masks and queens match permutation enumeration',()=>{for(const s of ['a','aab','aba','aaaa','abcba']){const expected=[];for(let mask=0;mask<2**(s.length-1);mask++){let start=0;const parts=[];for(let i=0;i<s.length;i++)if(i===s.length-1||mask&(1<<i)){parts.push(s.slice(start,i+1));start=i+1;}if(parts.every(p=>p===[...p].reverse().join('')))expected.push(parts);}const normalize=a=>a.map(row=>JSON.stringify(row)).sort();assert.deepEqual(normalize(solve('131')(s)),normalize(expected));assert.deepEqual(normalize(modules.get('131').buildTrace({s}).at(-1).answer),normalize(expected));}
 for(let n=1;n<=6;n++){const expected=[];function permute(path){if(path.length===n){if(path.every((c,r)=>path.every((d,s)=>r===s||Math.abs(c-d)!==Math.abs(r-s))))expected.push(path.map(c=>'.'.repeat(c)+'Q'+'.'.repeat(n-c-1)));return;}for(let c=0;c<n;c++)if(!path.includes(c))permute([...path,c]);}permute([]);const normalize=a=>a.map(row=>JSON.stringify(row)).sort();assert.deepEqual(normalize(solve('51')(n)),normalize(expected));assert.deepEqual(normalize(modules.get('51').buildTrace({n}).at(-1).answer),normalize(expected));}assert.equal(solve('51')(9).length,352);});
test('word search matches independent bit-mask path enumeration and restores the board',()=>{function reference(board,word){const m=board.length,n=board[0].length;function visit(r,c,i,mask){if(r<0||r>=m||c<0||c>=n||mask&(1<<(r*n+c))||board[r][c]!==word[i])return false;if(i===word.length-1)return true;mask|=1<<(r*n+c);return [[r+1,c],[r-1,c],[r,c+1],[r,c-1]].some(([a,b])=>visit(a,b,i+1,mask));}return board.some((row,r)=>row.some((_,c)=>visit(r,c,0,0)));}for(let trial=0;trial<80;trial++){const board=Array.from({length:2},(_,r)=>Array.from({length:3},(_,c)=>(trial>>(r*3+c))&1?'A':'B')),word=Array.from({length:1+trial%5},(_,i)=>(trial>>i)&1?'A':'B').join(''),before=structuredClone(board),expected=reference(board,word);assert.equal(solve('79')(board,word),expected);assert.deepEqual(board,before);const trace=modules.get('79').buildTrace({board,word});assert.equal(trace.at(-1).answer,expected);assert.deepEqual(trace.at(-1).visited,[]);}});
test('remaining cards map all phases independently in four languages',()=>{for(const [id,m] of modules)for(const e of m.examples)for(const s of m.buildTrace(e))for(const c of m.codes)assert.ok(c.source.split('\n')[c.lines[s.line]-1]?.trim(),`${id} ${c.id} ${s.line}`);});
