import test from 'node:test';import assert from 'node:assert/strict';
const modules=await Promise.all(['438','76','239','84'].map(async id=>({id,...await import(`../public/algorithm-cards/problems/${id}.js`),codes:(await import(`../public/algorithm-cards/problems/${id}-code.js`)).codes})));
const solve=modules.map(m=>new Function(`${m.codes[1].source};return ${m.codes[1].method};`)());
function anagrams(s,p){const sorted=[...p].sort().join('');return Array.from({length:Math.max(0,s.length-p.length+1)},(_,i)=>i).filter(i=>[...s.slice(i,i+p.length)].sort().join('')===sorted);}
function minWindow(s,t){let answer='';const need=new Map();for(const ch of t)need.set(ch,(need.get(ch)||0)+1);for(let l=0;l<s.length;l++)for(let r=l;r<s.length;r++){const counts=new Map();for(const ch of s.slice(l,r+1))counts.set(ch,(counts.get(ch)||0)+1);if([...need].every(([ch,n])=>(counts.get(ch)||0)>=n)&&(!answer||r-l+1<answer.length))answer=s.slice(l,r+1);}return answer;}
function rectangle(a){let best=0;for(let l=0;l<a.length;l++){let height=Infinity;for(let r=l;r<a.length;r++){height=Math.min(height,a[r]);best=Math.max(best,height*(r-l+1));}}return best;}
test('window and stack sources and traces agree with independent exhaustive references',()=>{let seed=239;const random=n=>((seed=(seed*1664525+1013904223)>>>0)%n);for(let trial=0;trial<250;trial++){const s=Array.from({length:1+random(8)},()=>String.fromCharCode(97+random(3))).join(''),p=Array.from({length:1+random(4)},()=>String.fromCharCode(97+random(3))).join(''),nums=Array.from({length:1+random(9)},()=>random(11)-5),k=1+random(nums.length),heights=nums.map(n=>Math.abs(n));const cases=[[{s,p},[s,p],anagrams(s,p)],[{s,t:p},[s,p],minWindow(s,p)],[{nums,k},[nums,k],nums.slice(k-1).map((_,i)=>Math.max(...nums.slice(i,i+k)))],[{heights},[heights],rectangle(heights)]];cases.forEach(([e,args,expected],i)=>{assert.deepEqual(solve[i](...args),expected);assert.deepEqual(modules[i].buildTrace(e).at(-1).answer,expected);});}});
test('every phase maps to an executed line in all languages and old snapshots remain unchanged',()=>{for(const m of modules)for(const e of m.examples){const trace=m.buildTrace(e),initial=structuredClone(trace[0]);for(const s of trace)for(const code of m.codes)assert.ok(code.source.split('\n')[code.lines[s.line]-1]?.trim(),`${m.id} ${code.id} ${s.line}`);assert.deepEqual(trace[0],initial);}});
test('valid maximum inputs exercise linear queue and stack algorithms',()=>{assert.equal(solve[2](Array(100000).fill(7),50000).length,50001);assert.equal(solve[3](Array(100000).fill(10000)),1000000000);assert.equal(solve[1]('A'.repeat(99999)+'B','AB'),'AB');assert.equal(solve[0]('a'.repeat(30000),'a'.repeat(30000))[0],0);});
