import test from 'node:test';import assert from 'node:assert/strict';
const ids=['1143','72','5'],modules=await Promise.all(ids.map(id=>import(`../public/algorithm-cards/problems/${id}.js`))),resources=await Promise.all(ids.map(id=>import(`../public/algorithm-cards/problems/${id}-code.js`)));
const solves=resources.map(({codes})=>new Function(`${codes[1].source};return ${codes[0].method};`)());
test('LCS matches exhaustive subsequence intersection',()=>{const strings=['a','b','ab','ba','aba','abb','aabb'];const subsequences=s=>new Set(Array.from({length:2**s.length},(_,mask)=>[...s].filter((_,i)=>mask&(1<<i)).join('')));for(const text1 of strings)for(const text2 of strings){const a=subsequences(text1),b=subsequences(text2),expected=Math.max(...[...a].filter(s=>b.has(s)).map(s=>s.length));assert.equal(solves[0](text1,text2),expected);assert.equal(modules[0].buildTrace({text1,text2}).at(-1).answer,expected);}});
test('edit distance matches BFS over actual insert/delete/replace operations',()=>{
 const strings=['','a','b','ab','ba','aaa','abb'];for(const word1 of strings)for(const word2 of strings){const limit=Math.max(word1.length,word2.length),queue=[[word1,0]],seen=new Set([word1]);let expected=null;for(let head=0;head<queue.length;head++){const [s,d]=queue[head];if(s===word2){expected=d;break;}const next=[];for(let i=0;i<s.length;i++){next.push(s.slice(0,i)+s.slice(i+1));for(const ch of 'ab')next.push(s.slice(0,i)+ch+s.slice(i+1));}if(s.length<limit)for(let i=0;i<=s.length;i++)for(const ch of 'ab')next.push(s.slice(0,i)+ch+s.slice(i));for(const value of next)if(!seen.has(value)){seen.add(value);queue.push([value,d+1]);}}assert.equal(solves[1](word1,word2),expected);assert.equal(modules[1].buildTrace({word1,word2}).at(-1).answer,expected);}
});
test('longest palindrome has maximal length among every contiguous substring',()=>{
 for(let n=1;n<=8;n++)for(let mask=0;mask<2**n;mask++){const s=Array.from({length:n},(_,i)=>mask&(1<<i)?'a':'b').join('');let length=0;for(let left=0;left<n;left++)for(let right=left+1;right<=n;right++){const value=s.slice(left,right);if(value===[...value].reverse().join(''))length=Math.max(length,value.length);}for(const answer of [solves[2](s),modules[2].buildTrace({s}).at(-1).answer]){assert.equal(answer.length,length);assert.ok(s.includes(answer));assert.equal(answer,[...answer].reverse().join(''));}}
});
test('prefix axes and phase mappings stay synchronized',()=>{for(let i=0;i<ids.length;i++)for(const e of modules[i].examples)for(const s of modules[i].buildTrace(e))for(const c of resources[i].codes)assert.ok(c.source.split('\n')[c.lines[s.line]-1]?.trim(),`${ids[i]} ${c.id} ${s.line}`);const trace=modules[1].buildTrace({word1:'ab',word2:''});assert.deepEqual(trace.at(-1).matrix,[[0],[1],[2]]);assert.equal(trace[0].i,null);assert.equal(trace[0].j,null);assert.equal(trace.find(s=>s.line==='baseRow').j,null);});
