import test from 'node:test';import assert from 'node:assert/strict';import {decodeTree,encodeTree} from '../public/algorithm-cards/shared/tree-card.js';
const ids=['230','226','543'],modules=await Promise.all(ids.map(id=>import(`../public/algorithm-cards/problems/${id}.js`))),resources=await Promise.all(ids.map(id=>import(`../public/algorithm-cards/problems/${id}-code.js`)));
const solves=resources.map(({codes})=>new Function(`${codes[1].source};return ${codes[0].method};`)());
test('BST selection matches sorted values for each valid rank',()=>{for(const input of [[2,1,3],[5,3,6,2,4,null,null,1],[1,null,2,null,3]]){const values=input.filter(v=>v!==null).sort((a,b)=>a-b);for(let k=1;k<=values.length;k++){assert.equal(solves[0](decodeTree(input),k),values[k-1]);assert.equal(modules[0].buildTrace({input,k}).at(-1).answer,values[k-1]);}}});
test('tree inversion preserves nodes and is an involution',()=>{for(const e of modules[1].examples){const tree=decodeTree(e.input),before=encodeTree(tree),result=solves[1](tree);assert.equal(result,tree);assert.deepEqual(modules[1].buildTrace(e).at(-1).answer,encodeTree(result));assert.deepEqual(encodeTree(solves[1](result)),before);}});
test('diameter matches all-pairs shortest paths on small trees',()=>{
 for(const input of [[1],[1,null,2,null,3],[1,2,3,4,5],[1,2,null,3,4,5,null,null,6],[]]){const tree=decodeTree(input),edges=new Map();function visit(node,parent=null){if(!node)return;edges.set(node.id,[]);if(parent){edges.get(node.id).push(parent.id);edges.get(parent.id).push(node.id);}visit(node.left,node);visit(node.right,node);}visit(tree);let expected=0;for(const start of edges.keys()){const seen=new Set([start]),q=[[start,0]];for(let i=0;i<q.length;i++){const [id,d]=q[i];expected=Math.max(expected,d);for(const next of edges.get(id))if(!seen.has(next)){seen.add(next);q.push([next,d+1]);}}}assert.equal(solves[2](tree),expected);assert.equal(modules[2].buildTrace({input}).at(-1).answer,expected);}
});
test('recursive phase mappings and saved topology are independent',()=>{for(let i=0;i<ids.length;i++)for(const e of modules[i].examples)for(const s of modules[i].buildTrace(e))for(const c of resources[i].codes)assert.ok(c.source.split('\n')[c.lines[s.line]-1]?.trim());const e=modules[1].examples[0],trace=modules[1].buildTrace(e);assert.deepEqual(encodeTree(trace[0].tree),e.input);assert.notDeepEqual(encodeTree(trace.at(-1).tree),e.input);});
